 services:
    db:
      image: postgres:latest
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=test_db  